### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by taniabogatsch** [taniabogatsch/turm#45]
- [x] Change the front end course fee pattern so that it allows inputs without a comma/dot
- [x] Scroll to 'more settings' after adding users to the blacklist/whitelist
- [x] If the course is active and edited -> If the field has dependencies -> get the course, set the field, validate the course -> only update the field if the validation is successful
- [x] If the course is active and edited -> send an e-mail to all enrolled users to notify them about the change (#36)
- [x] If the course is active -> show an eye-catching information message to the admin/creator/editor that upon editing the course, all enrolled users will be notified about the change
- [x] Expired courses cannot be edited
- [x] Add/edit/delete enrollment restrictions
- [x] Add/edit/delete enrollment key
- [x] Duplicate events
- [x] Duplicate meetings
- [x] Close download modal after course download
